# -*- coding: utf-8 -*-
"""AI_Spam_Classifier_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjvF1vo7yLyDHlApX_0-bnG6as7irzCN
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset1.csv',
    encoding='latin-1'
)

df.columns

print(df.shape)

print(df['label_num'].value_counts())

print(df.isnull().sum())

print(df.duplicated().sum())

df = df[['text', 'label_num']]

df.head()

df.columns = ['text', 'label']

df.head()

df.columns

"""#Doing text Text Preprocessing Setup:

#first installing required librarires:
"""

import nltk
import re
import string

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

"""#Creating Stemmer Object"""

ps = PorterStemmer()

"""#*Basic Preprocessing Function*"""

def preprocess_text(text):

    text = str(text)

    # lowercase er jonno
    text = text.lower()

    # remove urls er jonno
    text = re.sub(r'http\S+', '', text)

    # remove numbers er jonno
    text = re.sub(r'\d+', '', text)

    # remove punctuation er jonno
    text = text.translate(
        str.maketrans(
            '',
            '',
            string.punctuation
        )
    )

    # tokenize korer jonno
    words = text.split()

    # removing stopwords
    words = [
        word
        for word in words
        if word not in stopwords.words('english')
    ]

    # stemming er jonno
    words = [
        ps.stem(word)
        for word in words
    ]

    return " ".join(words)

"""# function test kori"""

sample = "Congratulations! You have won 10000 dollars. Click http://abc.com now."

print(preprocess_text(sample))

"""**Applying Preprocessing on Entire Dataset**"""

df['processed_text'] = df['text'].apply(preprocess_text)

"""*verifying*"""

df[['text', 'processed_text']].head()

"""*Checking processing worked correctly*"""

print(df['processed_text'].iloc[0])

"""# TF-IDF vectorization

*converting text to numerical features:*
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Creating TF-IDF object
vectorizer = TfidfVectorizer()

# Converting processed text into numerical features
X = vectorizer.fit_transform(df['processed_text'])

# Targeting variable
y = df['label']

# Checking shape
print("X shape:", X.shape)
print("y shape:", y.shape)

print(type(X))

"""# it's train-test splitting time"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

"""  #now we are trainning our naive bayes model:"""

from sklearn.naive_bayes import MultinomialNB

# Createing model
model = MultinomialNB()

# Training model
model.fit(X_train, y_train)

"""# Prediction:"""

y_pred = model.predict(X_test)

"""# Accuracy"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

"""# Confusion matrix:"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

"""# Confusion matrix visualization:"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""# here is the classification report"""

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print(cm)

print(classification_report(y_test, y_pred))

"""# saving the accuracy:"""

acc1 = accuracy

print("Dataset 1 Accuracy =", round(acc1*100,2), "%")

"""# Saving this Pipeline as a function"""

def evaluate_dataset(df):

    # copy dataframe
    df = df.copy()

    # preprocess
    df['processed_text'] = df['text'].apply(preprocess_text)

    # TF-IDF
    vectorizer = TfidfVectorizer()

    X = vectorizer.fit_transform(df['processed_text'])
    y = df['label']

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    # model
    model = MultinomialNB()
    model.fit(X_train, y_train)

    # prediction
    y_pred = model.predict(X_test)

    # accuracy
    accuracy = accuracy_score(y_test, y_pred)

    return accuracy

"""# Loading dataset-2:"""

import pandas as pd

df = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset2.csv',
    encoding='latin-1'
)

"""*reading dataset 2:*"""

print(df.columns)
print(df.shape)
df.head()

"""# Preparing dataset 2"""

df = df.rename(columns={
    'message':'text'
})

"""# Converting ham/spam ----> 0/1"""

df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

"""# Verifying"""

print(df['label'].value_counts())

"""# accuracy of dataset2"""

import pandas as pd

# Reloading df2 to correct the NaN values and ensure original state.
df2 = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset2.csv',
    encoding='latin-1'
)

# Renaming 'message' column to 'text' as expected by evaluate_dataset function.
df2 = df2.rename(columns={'message':'text'})

acc2 = evaluate_dataset(df2)

print("Dataset 2 Accuracy =", round(acc2*100,2), "%")

"""#for saving purpose"""

acc1 = 0.9256038647342996
acc2 = 0.9686

comparison = pd.DataFrame({
    'Dataset': ['Dataset 1', 'Dataset 2'],
    'Accuracy': [acc1, acc2]
})

comparison

"""# Dataset 3 loading:"""

import pandas as pd

df = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset3.csv',
    encoding='latin-1'
)

"""*reading*"""

print(df.columns)
print(df.shape)
df.head()

"""# REnameing the columns:"""

df = df.rename(columns={
    'spam': 'label'
})

"""# checking labels:"""

print(df['label'].value_counts())

"""# Accuracy of dataset-3:"""

acc3 = evaluate_dataset(df)

print("Dataset 3 Accuracy =", round(acc3*100,2), "%")

"""# Loading dataset-4"""

import pandas as pd

df = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset4.csv',
    encoding='latin-1'
)

"""**reading**

# Dataset 4-er columns and shape
"""

print(df.columns)
print(df.shape)

df.head()

"""# preparing dataset 4"""

df = df.rename(columns={
    'target': 'label'
})

"""*checking labels*"""

print(df['label'].value_counts())

"""# converting labels:"""

df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

"""#verifying"""

print(df['label'].value_counts())

"""# accuracy of dataset-4"""

import pandas as pd

# Reload df4 to ensure its original state from the CSV
df4 = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset4.csv',
    encoding='latin-1'
)

# Rename 'target' column to 'label' as expected by evaluate_dataset function.
df4 = df4.rename(columns={'target': 'label'})

# Convert 'ham' and 'spam' strings to numerical labels 0 and 1.
# This step is necessary because the original CSV contains 'spam'/'ham' strings
# and the evaluate_dataset function expects numeric labels.
df4['label'] = df4['label'].map({'ham': 0, 'spam': 1})

acc4 = evaluate_dataset(df4)

print("Dataset 4 Accuracy =", round(acc4*100,2), "%")

acc1 = 0.9256038647342996
acc2 = 0.9686
acc3 = 0.8831
acc4 = 0.8942

comparison = pd.DataFrame({
    'Dataset': [
        'Dataset 1',
        'Dataset 2',
        'Dataset 3',
        'Dataset 4'
    ],
    'Accuracy': [
        acc1,
        acc2,
        acc3,
        acc4
    ]
})

comparison

comparison['Accuracy (%)'] = comparison['Accuracy'] * 100

comparison

import pandas as pd

# --- Processing for Dataset 1 ---
df1 = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset1.csv',
    encoding='latin-1'
)
df1 = df1[['text', 'label_num']]
df1.columns = ['text', 'label']
df1_final = df1[['text', 'label']].copy()

# --- Processing for Dataset 2 ---
df2 = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset2.csv',
    encoding='latin-1'
)
df2 = df2.rename(columns={'message':'text'})
df2['label'] = df2['label'].map({
    'ham':0,
    'spam':1
})
df2_final = df2[['text', 'label']].copy()

# --- Processing for Dataset 3 ---
df3 = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset3.csv',
    encoding='latin-1'
)
df3 = df3.rename(columns={'spam': 'label'})
df3_final = df3[['text', 'label']].copy()

# --- Processing for Dataset 4 ---
df4 = pd.read_csv(
    '/content/drive/MyDrive/SpamClassifierProject/datasets/dataset4.csv',
    encoding='latin-1'
)
df4 = df4.rename(columns={'target': 'label'})
df4['label'] = df4['label'].map({
    'ham': 0,
    'spam': 1
})
df4_final = df4[['text', 'label']].copy()

print(df1_final.columns)
print(df2_final.columns)
print(df3_final.columns)
print(df4_final.columns)

"""# merging 4 datasets:"""

merged_df = pd.concat(
    [
        df1_final,
        df2_final,
        df3_final,
        df4_final
    ],
    ignore_index=True
)

print("Merged Shape:", merged_df.shape)

#checking lable distribution:

print(
    merged_df['label']
    .value_counts(dropna=False)
)

"""# merged dataset accuracy"""

merged_acc = evaluate_dataset(merged_df)

print(
    "Merged Dataset Accuracy =",
    round(merged_acc*100,2),
    "%"
)

"""# final Comparison er Code"""

comparison = pd.DataFrame({
    'Dataset': [
        'Dataset 1',
        'Dataset 2',
        'Dataset 3',
        'Dataset 4',
        'Merged Dataset'
    ],
    'Accuracy (%)': [
        round(acc1*100,2),
        round(acc2*100,2),
        round(acc3*100,2),
        round(acc4*100,2),
        round(merged_acc*100,2)
    ]
})

comparison

"""# Accuracy-graph:"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(
    comparison['Dataset'],
    comparison['Accuracy (%)']
)

plt.ylabel('Accuracy (%)')
plt.title('Accuracy comparison of individual & merged datasets')

plt.show()

"""# Saving the final model:"""

import joblib

joblib.dump(model, "spam_classifier.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

import os

print(os.listdir())

model = MultinomialNB()

model.fit(
    X_train,
    y_train
)

print(type(model))

print(model)

"""# Final model training:"""

merged_df['processed_text'] = merged_df['text'].apply(preprocess_text)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(
    merged_df['processed_text']
)

y = merged_df['label']

from sklearn.naive_bayes import MultinomialNB

final_model = MultinomialNB()

final_model.fit(X, y)

print("Final Model Trained Successfully")

"""#saving:"""

import joblib

joblib.dump(final_model,
            "final_spam_classifier.pkl")

joblib.dump(vectorizer,
            "final_tfidf_vectorizer.pkl")

print("Saved Successfully")

import os

print(os.listdir())

"""# training-test split on mergerd data"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""# Traininng model again:"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

"""#confusion matrix:"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

print(cm)

"""#drawing confusion matrix:"""

from sklearn.metrics import ConfusionMatrixDisplay

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Ham", "Spam"]
)

disp.plot()

plt.title("Confusion metrix")
plt.show()

"""#saving figure:"""

plt.figure(figsize=(6,4))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Ham", "Spam"]
)

disp.plot()


plt.savefig(
    '/content/drive/MyDrive/SpamClassifierProject/graphs/confusion_matrix.png',
    bbox_inches='tight'
)

plt.show()

"""#classification report:"""

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

"""#saving accuracy comparison graph"""

import matplotlib.pyplot as plt

datasets = [
    'Dataset 1',
    'Dataset 2',
    'Dataset 3',
    'Dataset 4',
    'Merged'
]

accuracies = [
    92.56,
    96.86,
    88.31,
    89.42,
    93.15
]

plt.figure(figsize=(8,5))

plt.bar(
    datasets,
    accuracies
)

plt.ylabel("Accuracy (%)")
plt.xlabel("Datasets")
plt.title("Accuracy Comparison of Individual and Merged Datasets")

plt.savefig(
    "/content/drive/MyDrive/SpamClassifierProject/graphs/accuracy_comparison.png",
    bbox_inches="tight"
)


plt.show()

"""#for checking purpose:"""

import os

print(os.listdir())

"""#model save in drive"""

import joblib

joblib.dump(
    final_model,
    '/content/drive/MyDrive/SpamClassifierProject/models/final_spam_classifier.pkl'
)

joblib.dump(
    vectorizer,
    '/content/drive/MyDrive/SpamClassifierProject/models/final_tfidf_vectorizer.pkl'
)

import joblib

# Load Final Model
model = joblib.load("final_spam_classifier.pkl")
vectorizer = joblib.load("final_tfidf_vectorizer.pkl")

while True:

    msg = input("Enter Message (type 'exit' to stop): ")

    if msg.lower() == "exit":
        print("Program Ended.")
        break

    # Preprocess
    msg_clean = preprocess_text(msg)

    # Vectorize
    msg_vector = vectorizer.transform([msg_clean])

    # Predict
    prediction = model.predict(msg_vector)

    if prediction[0] == 1:
        print("🚨 SPAM MESSAGE\n")
    else:
        print("✅ HAM (NOT SPAM)\n")

!pip install gradio

import gradio as gr
import joblib

model = joblib.load("final_spam_classifier.pkl")
vectorizer = joblib.load("final_tfidf_vectorizer.pkl")

def predict_spam(message):

    msg_clean = preprocess_text(message)

    msg_vector = vectorizer.transform([msg_clean])

    prediction = model.predict(msg_vector)

    if prediction[0] == 1:
        return "🚨 SPAM"
    else:
        return "✅ HAM"

app = gr.Interface(
    fn=predict_spam,
    inputs="text",
    outputs="text",
    title="AI Spam Message Classifier"
)

app.launch()